import { Button } from "@/components/ui/button";
import { Shield, Lock, Eye, FileText, ArrowLeft } from "lucide-react";
import Link from "next/link";
import { GlobalBackground } from "@/components/GlobalBackground";

import { PublicHeader } from "@/components/PublicHeader";
import { Footer } from "@/components/Footer";

export default function PrivacyPage() {
    const lastUpdated = "December 31, 2025";

    return (
        <div className="min-h-screen bg-[#0A0A0B] font-sans text-slate-200 overflow-x-hidden">
            <GlobalBackground />
            <PublicHeader />

            <main className="pt-32 pb-20">
                <div className="container mx-auto px-4 max-w-4xl">
                    <div className="mb-12">
                        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-sm font-medium mb-6">
                            <Shield className="h-4 w-4" />
                            Privacy Policy
                        </div>
                        <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">Your Privacy is Our Priority</h1>
                        <p className="text-slate-400">Last updated on {lastUpdated}</p>
                    </div>

                    <div className="grid md:grid-cols-3 gap-6 mb-16">
                        <div className="p-6 rounded-2xl bg-white/5 border border-white/10">
                            <Lock className="h-6 w-6 text-indigo-400 mb-4" />
                            <h3 className="text-white font-bold mb-2">Secure Data</h3>
                            <p className="text-sm text-slate-400">We use industry-standard encryption to protect your data.</p>
                        </div>
                        <div className="p-6 rounded-2xl bg-white/5 border border-white/10">
                            <Eye className="h-6 w-6 text-purple-400 mb-4" />
                            <h3 className="text-white font-bold mb-2">Transparency</h3>
                            <p className="text-sm text-slate-400">We are clear about what data we collect and why.</p>
                        </div>
                        <div className="p-6 rounded-2xl bg-white/5 border border-white/10">
                            <FileText className="h-6 w-6 text-pink-400 mb-4" />
                            <h3 className="text-white font-bold mb-2">User Control</h3>
                            <p className="text-sm text-slate-400">You can export or delete your data at any time.</p>
                        </div>
                    </div>

                    <div className="prose prose-invert max-w-none space-y-8 text-slate-400 leading-relaxed">
                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">1. Introduction</h2>
                            <p>
                                Arjuna AI ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and share information when you use our website and AI-powered interview preparation platform.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">2. Information We Collect</h2>
                            <h3 className="text-xl font-semibold text-white mb-2">A. Personal Information</h3>
                            <p>
                                When you create an account, we collect your name, email address, and profile picture (if provided via OAuth). If you subscribe to a paid plan, our payment processor collects your billing information.
                            </p>
                            <h3 className="text-xl font-semibold text-white mb-2">B. Usage Data</h3>
                            <p>
                                We collect data about your interview practice sessions, including audio recordings (only if explicitly enabled), typed responses, scores, and feedback generated by our AI models.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">3. How We Use Your Information</h2>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>To provide and maintain our service</li>
                                <li>To generate personalized interview feedback and scores</li>
                                <li>To improve our AI models and user experience</li>
                                <li>To communicate with you about your account and updates</li>
                                <li>To prevent fraud and ensure security</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">4. Data Storage and Security</h2>
                            <p>
                                We use Supabase for data storage and authentication. Your data is stored securely in encrypted databases. We implement a variety of security measures to maintain the safety of your personal information.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">5. Your Rights</h2>
                            <p>
                                You have the right to access, correct, or delete your personal data. You can perform most of these actions directly within your account settings. If you need assistance, please contact us at support@arjuna.ai.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">6. Changes to This Policy</h2>
                            <p>
                                We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.
                            </p>
                        </section>
                    </div>
                </div>
            </main>

            <Footer />
        </div>
    );
}
